#!/bin/bash

if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]
then
 
   echo "

Initialize Ceph RBD-Provisioner

***Must validate ceph configuration before using this command***

Check 'kubectl ceph validate -h' for details
   
Usage:

  kubectl ceph init
  
        
Flags:
  -h, --help   help for kubectl ceph init  "
   exit 0
   
 fi

progress-bar() {
  local duration=${1}


    already_done() { for ((done=0; done<$elapsed; done++)); do printf "▇"; done }
    remaining() { for ((remain=$elapsed; remain<$duration; remain++)); do printf " "; done }
    percentage() { printf "| %s%%" $(( (($elapsed)*100)/($duration)*100/100 )); }
    clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=$duration; elapsed++ )); do
      already_done; remaining; percentage
      sleep 1
      clean_line
  done
  clean_line
} 

curl -s https://raw.githubusercontent.com/rahulwaykos/k8s-ceph/master/scripts/rbd-provisioner.sh | sh > /dev/null 2>&1


kubectl get pods -l app=rbd-provisioner -n kube-system
if [[ "$?" == "0" ]] 
then
echo -e "\nInitializing... Waiting for Pod to create"
progress-bar 35
echo -e "\n"
fi



