#!/bin/bash

if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]
then
 
   echo "

Initialize Ceph RBD-Provisioner

***Must validate ceph configuration before using this command***

Check 'kubectl ceph validate -h' for details
   
Usage:

  kubectl ceph init
  
        
Flags:
  -h, --help   help for kubectl ceph init  "
   exit 0
   
 fi
 
curl -s https://raw.githubusercontent.com/rahulwaykos/k8s-ceph/master/scripts/rbd-provisioner.sh | sh > /dev/null 2>&1
