#!/bin/bash

if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]
then
 
   echo "

Validate command used to validate the ceph authorized configuration and keyring provided by ceph-cluster admin

Usage:

  kubectl ceph validate
  
Flags:
  -h, --help   help for kubectl ceph create  "
   exit 0
   
 fi
 
 if [[ -f /etc/ceph/ceph.* ]] 
 then
   echo "Validating Ceph conf and keyring in /etc/ceph......"
   ceph -s > /dev/null
   if [[ "$?" == "0" ]]
   then
     echo " Validation Successful...!"
     echo -e "\n You can use kubectl ceph init command"
   else
     echo "Validation Failed!! Please check ceph.conf and keyring"
 else
   echo "No Files found in /etc/ceph"
 fi 
 
 
