#!/bin/bash

if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]
then
 
   echo "

Validate command used to validate the ceph authorized configuration and keyring provided by ceph-cluster admin

Usage:

  kubectl ceph validate
  
Flags:
  -h, --help   help for kubectl ceph create  "
   exit 0
   
 fi

progress-bar() {
  local duration=${1}


    already_done() { for ((done=0; done<$elapsed; done++)); do printf "▇"; done }
    remaining() { for ((remain=$elapsed; remain<$duration; remain++)); do printf " "; done }
    percentage() { printf "| %s%%" $(( (($elapsed)*100)/($duration)*100/100 )); }
    clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=$duration; elapsed++ )); do
      already_done; remaining; percentage
      sleep 1
      clean_line
  done
  clean_line
}

validate () {
file="/etc/ceph/ceph.conf"
file1="/etc/ceph/ceph.client.admin.keyring"

if [[ -f "$file" ]] && [[ -f "$file1" ]] 
then
   echo "Validating Ceph conf and keyring in /etc/ceph......"
   progress-bar 10
   ceph -s > /dev/null 2>&1
     if [[ "$?" == "0" ]]
      then
          echo " Validation Successful...!"
          echo -e "\n You can use kubectl ceph init command"
      else
          echo "Validation Failed!! Please check ceph.conf and keyring"
      fi
else
   echo "No Files found in /etc/ceph"
fi 
 
 }
 
 validate
