#!/bin/bash

if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]
then
 
   echo "

Creates the PVC for k8s. Ceph RBD as backend

Usage:

  kubectl ceph create -n [name] -s [size] or
  kubectl ceph create --name=[name] --size=[size}
  
  name      Name for PVC to create
  size      Size in GB for pvc to claim
  
Flags:
  -h, --help   help for kubectl ceph create  "
   exit 0
   
 fi
 
 

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -n|--name=*)
    if [[ "$key" == "-n" ]]; then
    NAME="$2"
    shift # past argument
    shift # past value
    else
    NAME="${key#*=}"
    shift
    fi
    ;;
    -s|--size=*)
    if [[ "$key" == "-s" ]]; then
    SIZE="$2"
    shift # past argument
    shift # past value
    else
    SIZE="${key#*=}"
    shift
    fi
    ;;
esac
done
set -- "${POSITIONAL[@]}"

if [[ -z "$NAME" ]] | [[ -z "$SIZE" ]]
then
    echo -e "    No valid option!! \n See 'kubectl ceph create --help' for more details"
else
cat <<EOF | kubectl apply -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${SIZE}Gi
  storageClassName: storage-rbd
EOF
fi




